backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This should provide a URL to your published site
site_url: https://benjamin.caradeuc.info

# This will include a link in the fixed area at the top of the page, allowing content authors to easily return to your main site
display_url: https://benjamin.caradeuc.info

# This will change the logo displayed at the top of the login page
logo_url: https://benjamin.caradeuc.info/images/avatar.png

# Media files will be stored in the repo under images/uploads
media_folder: "source/images/uploads"

# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"

locale: 'fr'

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Benjamin Caradeuc"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Featured Image thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: pages
    label: Pages
    files:
      - label: "About"
        name: about
        file: "source/about/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "thumbnail", widget: "image"}
          - {label: "Template", name: "template", widget: "hidden", default: "about"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Contact"
        name: contact
        file: "source/contact/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "thumbnail", widget: "image"}
          - {label: "Template", name: "template", widget: "hidden", default: "contact"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Contact Success"
        name: contact-success
        file: "source/contact/success.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "thumbnail", widget: "image"}
          - {label: "Sitemap", name: "sitemap", widget: "hidden", default: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Tags"
        name: tags
        file: "source/tags/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "thumbnail", widget: "image"}
          - {label: "Template", name: "template", widget: "hidden", default: "tags"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "404"
        name: not_found
        file: "source/404.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "thumbnail", widget: "image"}
          - {label: "Template", name: "template", widget: "hidden", default: "404"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "data"
    label: "Data"
    editor:
      preview: false
    files:
      - label: "Menu"
        name: "menu"
        file: "source/_data/menu.yml"
        fields:
          - label: Menu items
            name: menuItems
            widget: list
            allow_add: false
            fields:
              - name: key
                label: 'Key'
                widget: string
              - name: title
                label: 'Title'
                widget: string
              - name: path
                label: Path
                widget: string
              # - name: path
              #   label: Path
              #   widget: "relation"
              #   collection: "posts"
              #   searchFields: ["title", "author"]
              #   valueField: "title"
              #   displayFields: ["title", "author", "date"]

      - label: "Social"
        name: "social"
        file: "source/_data/social.yml"
        fields:
          - label: Social
            name: socialItems
            widget: list
            allow_add: false
            fields:
              - name: key
                label: 'Key'
                widget: string
              - name: name
                label: 'Name'
                widget: string
              - name: color
                label: 'Color'
                widget: color
              - name: sharer_url
                label: 'Sharer URL'
                widget: string

      - label: CV
        name: about
        file: "source/_data/about.yml"
        fields:
          - label: Timelines
            name: timelines
            widget: list
            fields:
              - name: title
                label: Titre
                widget: string
              - name: items
                label: items
                widget: list
                fields:
                  - name: name
                    label: Name
                    widget: string
                  - name: period
                    label: Period
                    widget: string
                  - name: establishment
                    label: Establishment
                    widget: string
                  - name: location
                    label: Location
                    widget: string
                  - name: description
                    label: Description
                    widget: markdown
                  - name: tags
                    label: Tags
                    widget: list
                    fields:
                      - name: name
                        label: Name
                        widget: string
                      - name: color
                        label: Color
                        widget: select
                        options:
                          - green
                          - yellow
                          - orange
                          - blue
                          - red
                          - violet
                          - gray
