sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false
  includePaths:
    - 'node_modules/normalize-scss/sass/'

default_header_img: '/images/default_img.jpg'
# default_header_img: 'https://images.unsplash.com/photo-1508904186271-c9c83ae788cb?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=10cd33d3da51eec540e8021cece867b4&auto=format&fit=crop&w=1350&q=80'
